# Generated by Django 5.1.3 on 2024-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bank_loan_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_loan',
            name='ifsc',
        ),
        migrations.AlterField(
            model_name='bank_loan',
            name='Accno',
            field=models.IntegerField(),
        ),
    ]
